name: Gradle CI/CD Workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                    java-version: '21'

            - name: Cache Gradle packages
              uses: actions/cache@v3
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
                  restore-keys: ${{ runner.os }}-gradle

            - name: Build with Gradle
              run: ./gradlew build --no-daemon

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                    java-version: '21'

            - name: Run Tests with Gradle
              run: ./gradlew test --no-daemon


    coverage:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                    java-version: '21'
            - name: Run Coverage with Gradle
              run: ./gradlew jacocoTestReport --no-daemon

            - name: Upload Coverage Report
              uses: codecov/codecov-action@v3
              with:
                name: jococo-report
                path: build/reports/jacoco/test/jacocoTestReport.xml

    analyze:
        runs-on: ubuntu-latest
        needs: coverage
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                    java-version: '21'
            - name: Run SonarQube with Gradle
              run: ./gradlew sonarqube --no-daemon

    deploy:
        runs-on: ubuntu-latest
        needs: analyze
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                    java-version: '21'
            - name: Deploy to Production
              run: echo "Deploying to production" # TODO