version: '3.4'

services:
    postgres:
        image: postgres:17
        container_name: library-postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=library
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    app:
        image: library-application
        container_name: library-app
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/library
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        ports:
            - "8080:8080"
        depends_on:
            - postgres

volumes:
    postgres_data: